#!/usr/bin/env node
"use strict"

var c = require('skilstak-colors')
function printPlain() {
  
  console.log("Hello World");
}
var printColor = function (message) {

  console.log(c.b + message)

}
var printMulti = function (message) {
  
  console.log(c.y + message)
}



printColor("troy is boring");
printMulti("troy is not as cool as me");




