#!/usr/bin/env node
"use strict"

var c = require('skilstak-colors')
function printPlain() {
  
  console.log("Hello World");
}
var printPlain = function () {

  console.log(c Blue)




printPlain();
