#!/usr/bin/env python3
import skilstak.colors as c
import time

def print_plain()
    (c.clear + c.rc() + "hello" + c.rc() + "world")
    """clear screen and prints helloworld"""
    

def print_multi():
    """prints helloworld in multiple colors"""
    while True:
        print(c.clear + c.multi("hello world"))
        time.sleep(0.5)
    
def print_color():
    """fill screen with randomly color helloworld"""
    print(c.clear)
    while True:
        print(c.rc() + "helloworld" + c.reset, end=" ")  
        

def parse_argsZZ ():
    """runs helloworld"""
    try:
        while True:
            print(c.clear + c.rc() + "hello" + c.rc() + "world")
    except KeyboardInterrupt:
        exit()
if __name__ == '__main__':
    import sys
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
