#!/usr/bin/env python3
import skilstak.colors as c
import time

def plain()
    """clear screen and prints helloworld"""
    print(c.clear + c.rc() + "hello" + c.rc() + "world")

def multi():
    """prints helloworld in multiple colors"""
    while True:
        print(c.clear + c.multi("hello world"))
        time.sleep(0.5)
    
def hello():
    """runs helloworld"""
    try:
        while True:
            print(c.clear + c.rc() + "hello" + c.rc() + "world")
    except KeyboardInterrupt:
        exit()
if __name__ == '__main__':
    import sys
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
