#!/usr/bin/env python3
"""My super cool Python hello world program"""
import skilstak.colors as c
def print_plain(message):
    
    """print < message > in plain""" 
    print(message)
def print_rainbow(message):    
    while True:
    """print < message > in rainbow"""

    print(message  c)
def    
if __name__ == "__main__":
    print_plain("hello world")

    
